CREATE TABLE NACIONALIDAD (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CODIGO CHAR(2),
    NOMBRE VARCHAR(20) NOT NULL,
    CONSTRAINT ID_NACIONALIDAD_PK PRIMARY KEY (ID)
);


CREATE TABLE JUGADORES (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDOS VARCHAR(40) NOT NULL,
    NACIONALIDAD INTEGER NOT NULL,
    FECHA_NACIMIENTO DATE,
    VALORACION SMALLINT,
    PRECIO_CARTA DECIMAL(10,2),
    RETIRADO BOOLEAN,
    LIGA VARCHAR(40),
    FOTO VARCHAR(30),
    CONSTRAINT ID_JUGADORES_PK PRIMARY KEY (ID),
    CONSTRAINT NAC_JUGADORES_FK FOREIGN KEY (NACIONALIDAD) REFERENCES NACIONALIDAD (ID)
);